//
// File generated by rootcint at Mon Jul 22 10:51:48 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TSelector_SusyNtupledIPROOFmIINFdIdOdOdImmcdIdImmcCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mmcCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void mmc_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void mmc_Dictionary();
   static void *new_mmc(void *p = 0);
   static void *newArray_mmc(Long_t size, void *p);
   static void delete_mmc(void *p);
   static void deleteArray_mmc(void *p);
   static void destruct_mmc(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::mmc*)
   {
      ::mmc *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::mmc),0);
      static ::ROOT::TGenericClassInfo 
         instance("mmc", "./TSelector_SusyNtuple/PROOF-INF/../mmc//mmc.hpp", 22,
                  typeid(::mmc), DefineBehavior(ptr, ptr),
                  0, &mmc_Dictionary, isa_proxy, 0,
                  sizeof(::mmc) );
      instance.SetNew(&new_mmc);
      instance.SetNewArray(&newArray_mmc);
      instance.SetDelete(&delete_mmc);
      instance.SetDeleteArray(&deleteArray_mmc);
      instance.SetDestructor(&destruct_mmc);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::mmc*)
   {
      return GenerateInitInstanceLocal((::mmc*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::mmc*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void mmc_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::mmc*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_mmc(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mmc : new ::mmc;
   }
   static void *newArray_mmc(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mmc[nElements] : new ::mmc[nElements];
   }
   // Wrapper around operator delete
   static void delete_mmc(void *p) {
      delete ((::mmc*)p);
   }
   static void deleteArray_mmc(void *p) {
      delete [] ((::mmc*)p);
   }
   static void destruct_mmc(void *p) {
      typedef ::mmc current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::mmc

/********************************************************
* TSelector_SusyNtuple/PROOF-INF/../mmc//mmcCint.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemmcCint();

extern "C" void G__set_cpp_environmentmmcCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TSelector_SusyNtuple/PROOF-INF/../mmc//mmc.hpp");
  G__cpp_reset_tagtablemmcCint();
}
#include <new>
extern "C" int G__cpp_dllrevmmcCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* mmc */
static int G__mmcCint_317_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mmc* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mmc((int) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) mmc((int) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new mmc[n];
       } else {
         p = new((void*) gvp) mmc[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new mmc;
       } else {
         p = new((void*) gvp) mmc;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mmcCintLN_mmc));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->Scan6d(*((const TLorentzVector*) G__int(libp->para[0])), *((const TLorentzVector*) G__int(libp->para[1]))
, (const float) G__double(libp->para[2]), (const float) G__double(libp->para[3])
, (const float) G__double(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->Scan6dTheta(*((const TLorentzVector*) G__int(libp->para[0])), *((const TLorentzVector*) G__int(libp->para[1]))
, (const float) G__double(libp->para[2]), (const float) G__double(libp->para[3])
, (const float) G__double(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->Scan4dTheta(*((const TLorentzVector*) G__int(libp->para[0])), *((const TLorentzVector*) G__int(libp->para[1]))
, (const float) G__double(libp->para[2]), (const float) G__double(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->Scan6dAnal(*((const TLorentzVector*) G__int(libp->para[0])), *((const TLorentzVector*) G__int(libp->para[1]))
, (const float) G__double(libp->para[2]), (const float) G__double(libp->para[3])
, (const float) G__double(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->Scan4dAnal(*((const TLorentzVector*) G__int(libp->para[0])), *((const TLorentzVector*) G__int(libp->para[1]))
, (const float) G__double(libp->para[2]), (const float) G__double(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetCollMass(*((const TLorentzVector*) G__int(libp->para[0])), *((const TLorentzVector*) G__int(libp->para[1]))
, (const float) G__double(libp->para[2]), (const float) G__double(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((mmc*) G__getstructoffset())->SetAngleWeight((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((mmc*) G__getstructoffset())->SetAngleWeight();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((mmc*) G__getstructoffset())->SetMassWeight((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((mmc*) G__getstructoffset())->SetMassWeight();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetMZ_peak());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetMZ_mean());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetMZ_maxprob());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetMZ_coll());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetExecTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetCorrMEX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((mmc*) G__getstructoffset())->GetCorrMEY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetPhi_N((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetTheta_N((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMet_N((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMMa_N((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetPhi_Lim((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetTheta_Lim((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMet_Lim((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMMa_LimLow((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMMa_LimHigh((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMet_S((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMet_LimSigma((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->SetMet_ScanMode((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->Set_Alpha((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mmcCint_317_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mmc*) G__getstructoffset())->Set_METNoise((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mmcCint_317_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   mmc* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new mmc(*(mmc*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mmcCintLN_mmc));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef mmc G__Tmmc;
static int G__mmcCint_317_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (mmc*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((mmc*) (soff+(sizeof(mmc)*i)))->~G__Tmmc();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (mmc*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((mmc*) (soff))->~G__Tmmc();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mmcCint_317_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mmc* dest = (mmc*) G__getstructoffset();
   *dest = *(mmc*) libp->para[0].ref;
   const mmc& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* mmc */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmmcCint {
 public:
  G__Sizep2memfuncmmcCint(): p(&G__Sizep2memfuncmmcCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmmcCint::*p)();
};

size_t G__get_sizep2memfuncmmcCint()
{
  G__Sizep2memfuncmmcCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemmcCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemmcCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mmcCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mmcCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mmcCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mmcCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mmcCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mmcCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mmcCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mmcCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mmcCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mmcCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__mmcCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* mmc */
static void G__setup_memvarmmc(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mmcCintLN_mmc));
   { mmc *p; p=(mmc*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_debug=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mz_peak=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mz_mean=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mz_maxprob=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mz_coll=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"Corr_met_ex=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"Corr_met_ey=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_weight=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_mm_weight=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mmcCintLN_TF1),-1,-1,4,"f_dR_weight[16]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mmcCintLN_TF1),-1,-1,4,"f_dTheta_weight[18]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mmcCintLN_TF1),-1,-1,4,"f_m_weight=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_phi_n=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_theta_n=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_met_n=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mma_n=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_costheta=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"theta_star_max=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"f_cut=",0,"define f_cut = lep_ptCUT / tauPT");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mma_n_4D=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mma_n_6D=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_costheta_4D=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_costheta_6D=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_phi_lim=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_theta_lim=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_met_lim=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mma_limlow=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_mma_limhigh=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_met_scanmode=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_met_limsigma=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_met_s=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"MET_scan_points_Phi=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"MET_scan_points_Z=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_exectime=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_alpha=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_noise=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmmcCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncmmc(void) {
   /* mmc */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mmcCintLN_mmc));
   G__memfunc_setup("mmc",317,G__mmcCint_317_0_1, 105, G__get_linked_tagnum(&G__mmcCintLN_mmc), -1, 0, 1, 1, 1, 0, "i - - 0 '3' wchoice", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__mmcCint_317_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Scan6d",543,G__mmcCint_317_0_3, 102, -1, -1, 0, 5, 1, 1, 0, 
"u 'TLorentzVector' - 10 - _lep1 u 'TLorentzVector' - 10 - _lep2 "
"f - - 10 - _metx f - - 10 - _mety "
"f - - 10 - _sumet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Scan6dTheta",1045,G__mmcCint_317_0_4, 102, -1, -1, 0, 5, 1, 1, 0, 
"u 'TLorentzVector' - 10 - _lep1 u 'TLorentzVector' - 10 - _lep2 "
"f - - 10 - _metx f - - 10 - _mety "
"f - - 10 - _sumet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Scan4dTheta",1043,G__mmcCint_317_0_5, 102, -1, -1, 0, 4, 1, 1, 0, 
"u 'TLorentzVector' - 10 - _lep1 u 'TLorentzVector' - 10 - _lep2 "
"f - - 10 - _metx f - - 10 - _mety", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Scan6dAnal",923,G__mmcCint_317_0_6, 102, -1, -1, 0, 5, 1, 1, 0, 
"u 'TLorentzVector' - 10 - _lep1 u 'TLorentzVector' - 10 - _lep2 "
"f - - 10 - _metx f - - 10 - _mety "
"f - - 10 - sigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Scan4dAnal",921,G__mmcCint_317_0_7, 102, -1, -1, 0, 4, 1, 1, 0, 
"u 'TLorentzVector' - 10 - _lep1 u 'TLorentzVector' - 10 - _lep2 "
"f - - 10 - _metx f - - 10 - _mety", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCollMass",1086,G__mmcCint_317_0_8, 102, -1, -1, 0, 4, 1, 1, 0, 
"u 'TLorentzVector' - 10 - _lep1 u 'TLorentzVector' - 10 - _lep2 "
"f - - 10 - _metx f - - 10 - _mety", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAngleWeight",1403,G__mmcCint_317_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '0' choice", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMassWeight",1320,G__mmcCint_317_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '1' choice", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMZ_peak",967,G__mmcCint_317_0_11, 102, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMZ_mean",967,G__mmcCint_317_0_12, 102, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMZ_maxprob",1311,G__mmcCint_317_0_13, 102, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMZ_coll",976,G__mmcCint_317_0_14, 102, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetExecTime",1076,G__mmcCint_317_0_15, 102, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCorrMEX",928,G__mmcCint_317_0_16, 102, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCorrMEY",929,G__mmcCint_317_0_17, 102, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPhi_N",762,G__mmcCint_317_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTheta_N",975,G__mmcCint_317_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMet_N",767,G__mmcCint_317_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMMa_N",724,G__mmcCint_317_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPhi_Lim",974,G__mmcCint_317_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTheta_Lim",1187,G__mmcCint_317_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMet_Lim",979,G__mmcCint_317_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMMa_LimLow",1242,G__mmcCint_317_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMMa_LimHigh",1320,G__mmcCint_317_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMet_S",772,G__mmcCint_317_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMet_LimSigma",1476,G__mmcCint_317_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMet_ScanMode",1467,G__mmcCint_317_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Set_Alpha",881,G__mmcCint_317_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Set_METNoise",1135,G__mmcCint_317_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - arg1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadFunc",776,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__mmcCintLN_TF1), -1, 0, 3, 1, 4, 0, 
"U 'TFile' - 0 - _file u 'TString' - 0 - histName "
"u 'TString' - 0 - taumu", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDeltaRDistribution",2140,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDeltaThetaDistribution",2560,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMDistribution",1645,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMETValue",1027,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 2, 1, 4, 0, 
"f - - 0 - met f - - 0 - sigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDeltaRValue",1369,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 2, 1, 4, 0, 
"f - - 0 - dR1 f - - 0 - pt1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDeltaThetaValue",1789,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 2, 1, 4, 0, 
"f - - 0 - dTheta1 f - - 0 - pt1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMValue",874,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 1, 1, 4, 0, "f - - 0 - m1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAnaWeight_TauMiss",1981,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 3, 1, 4, 0, 
"u 'TLorentzVector' - 10 - tau u 'TLorentzVector' - 10 - miss "
"f - - 1 - ntheta3d", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetJacobian",1079,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 6, 1, 4, 0, 
"u 'TLorentzVector' - 10 - vis_pos u 'TLorentzVector' - 10 - vis_neg "
"u 'TLorentzVector' - 10 - miss_pos u 'TLorentzVector' - 10 - miss_neg "
"f - - 10 - _Ex_miss f - - 10 - _Ey_miss", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMZ_peak",979,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "f - - 0 - mz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMZ_mean",979,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "f - - 0 - mz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMZ_maxprob",1323,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "f - - 0 - mz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMZ_coll",988,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "f - - 0 - mz", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("mmc", 317, G__mmcCint_317_0_46, (int) ('i'), G__get_linked_tagnum(&G__mmcCintLN_mmc), -1, 0, 1, 1, 1, 0, "u 'mmc' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~mmc", 443, G__mmcCint_317_0_47, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mmcCint_317_0_48, (int) ('u'), G__get_linked_tagnum(&G__mmcCintLN_mmc), -1, 1, 1, 1, 1, 0, "u 'mmc' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmmcCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmmcCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmmcCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mmcCintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__mmcCintLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__mmcCintLN_mmc = { "mmc" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemmcCint() {
  G__mmcCintLN_TString.tagnum = -1 ;
  G__mmcCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mmcCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mmcCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mmcCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__mmcCintLN_TFile.tagnum = -1 ;
  G__mmcCintLN_TF1.tagnum = -1 ;
  G__mmcCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__mmcCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__mmcCintLN_TLorentzVector.tagnum = -1 ;
  G__mmcCintLN_mmc.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemmcCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TString);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TFile);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TF1);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__mmcCintLN_TLorentzVector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mmcCintLN_mmc),sizeof(mmc),-1,256,(char*)NULL,G__setup_memvarmmc,G__setup_memfuncmmc);
}
extern "C" void G__cpp_setupmmcCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupmmcCint()");
  G__set_cpp_environmentmmcCint();
  G__cpp_setup_tagtablemmcCint();

  G__cpp_setup_inheritancemmcCint();

  G__cpp_setup_typetablemmcCint();

  G__cpp_setup_memvarmmcCint();

  G__cpp_setup_memfuncmmcCint();
  G__cpp_setup_globalmmcCint();
  G__cpp_setup_funcmmcCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmmcCint();
  return;
}
class G__cpp_setup_initmmcCint {
  public:
    G__cpp_setup_initmmcCint() { G__add_setup_func("mmcCint",(G__incsetup)(&G__cpp_setupmmcCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmmcCint() { G__remove_setup_func("mmcCint"); }
};
G__cpp_setup_initmmcCint G__cpp_setup_initializermmcCint;

