/********************************************************************
* TSelector_SusyNtuple/PROOF-INF/../mmc//mmcCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSelector_SusyNtuple/PROOF-INF/../mmc//mmcCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemmcCint();
extern void G__cpp_setup_inheritancemmcCint();
extern void G__cpp_setup_typetablemmcCint();
extern void G__cpp_setup_memvarmmcCint();
extern void G__cpp_setup_globalmmcCint();
extern void G__cpp_setup_memfuncmmcCint();
extern void G__cpp_setup_funcmmcCint();
extern void G__set_cpp_environmentmmcCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TSelector_SusyNtuple/PROOF-INF/../mmc//mmc.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mmcCintLN_TString;
extern G__linked_taginfo G__mmcCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mmcCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mmcCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mmcCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mmcCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mmcCintLN_TFile;
extern G__linked_taginfo G__mmcCintLN_TF1;
extern G__linked_taginfo G__mmcCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__mmcCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__mmcCintLN_TLorentzVector;
extern G__linked_taginfo G__mmcCintLN_mmc;

/* STUB derived class for protected member access */
